name: vitrocal
channels:
  - defaults
  - conda-forge
dependencies:
  - accelerate=0.31.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.18.0
  - astroid=3.2.2
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - babel=2.14.0
  - backports=1.1
  - backports.tarfile=1.0.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.12.3
  - black=24.4.2
  - blas=2.122
  - blas-devel=3.9.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - build=0.10.0
  - bump2version=1.0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - cctools_osx-arm64=986
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfgv=3.4.0
  - charset-normalizer=3.3.2
  - clang=16.0.6
  - clang-16=16.0.6
  - clang_impl_osx-arm64=16.0.6
  - clang_osx-arm64=16.0.6
  - clangxx=16.0.6
  - clangxx_impl_osx-arm64=16.0.6
  - clangxx_osx-arm64=16.0.6
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmarkgfm=2022.10.27
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=16.0.6
  - compiler-rt_osx-arm64=16.0.6
  - cons=0.4.6
  - contourpy=1.2.1
  - coverage=7.5.3
  - cycler=0.12.1
  - darglint=1.8.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distlib=0.3.8
  - dm-tree=0.1.8
  - docutils=0.21.2
  - entrypoints=0.4
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.15.1
  - flake8=7.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2024.6.0
  - gdk-pixbuf=2.42.12
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - ghp-import=2.1.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.14
  - graphviz=11.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.23.3
  - humanize=4.9.0
  - hyperframe=6.0.1
  - hypothesis=6.103.1
  - icu=73.2
  - identify=2.5.36
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - interrogate=1.7.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - isort=5.13.2
  - jaraco.classes=3.4.0
  - jaraco.context=5.3.0
  - jaraco.functools=4.0.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - keyring=25.2.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld64_osx-arm64=711
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp16=16.0.6
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - librsvg=2.58.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  # - libtorch=2.3.0
  - libuv=1.48.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.7
  - llvm-tools=16.0.6
  - logical-unification=0.4.6
  - macosx_deployment_target_osx-arm64=11.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mergedeep=1.3.4
  - minikanren=1.0.3
  - mistune=3.0.2
  - mkdocs=1.6.0
  - mkdocs-autorefs=1.0.1
  - mkdocs-get-deps=0.2.0
  - mkdocs-material=9.5.26
  - mkdocs-material-extensions=1.3.1
  - mkdocstrings=0.25.1
  - more-itertools=10.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multimethod=1.9.1
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nh3=0.2.17
  - nodeenv=1.9.1
  - nomkl=3.0
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - paginate=0.5.6
  - pandas=2.2.2
  - pandera=0.19.3
  - pandera-base=0.19.3
  - pandoc=3.2
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pins=0.8.6
  - pip=24.0
  - pixman=0.43.4
  - pkginfo=1.11.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pre-commit=3.7.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycodestyle=2.11.1
  - pycparser=2.22
  - pydantic=2.7.4
  - pydantic-core=2.18.4
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pylint=3.2.3
  - pymc=5.15.1
  - pymc-base=5.15.1
  - pymdown-extensions=10.8.1
  - pyobjc-core=10.2
  - pyobjc-framework-cocoa=10.2
  - pyparsing=3.1.2
  - pyproject_hooks=1.1.0
  - pyprojroot=0.3.0
  - pysocks=1.7.1
  - pytensor=2.22.1
  - pytensor-base=2.22.1
  - pytest=8.2.2
  - pytest-cov=5.0.0
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.3.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyyaml-env-tag=0.1
  - pyzmq=26.0.3
  - readline=8.2
  - readme_renderer=42.0
  - referencing=0.35.1
  - regex=2024.5.15
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986=2.0.0
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.18.1
  - safetensors=0.4.3
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=70.0.0
  - shellingham=1.5.4
  - sigtool=0.1.3
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - sympy=1.12
  - tabulate=0.9.0
  - tapi=1100.0.11
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.5
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  # - twine=5.1.0
  - typeguard=4.3.0
  - typer=0.12.3
  - typer-cli=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - virtualenv=20.26.2
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - xarray=2024.5.0
  - xarray-einstats=0.7.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - duckdb==1.0.0
      - et-xmlfile==1.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - mknotebooks==0.8.0
      - openpyxl==3.1.4
      - smmap==5.0.1
      # - vitrocal==0.0.1
